import type { NextPage } from 'next'
import Head from 'next/head'
import { TemplateBase } from '../templates/TemplateBase'


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Anderson Dias | Meu web site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TemplateBase>
        <h1>Hello word</h1>
      </TemplateBase>
    </>
  )
}

export default Home
