import type { NextPage } from 'next'
import Head from 'next/head'

export function Page() {
  return <Home />
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Anderson Dias | Meu web site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home
