import 'swiper/css'
import { Sliders } from '../components/Projects/Carrousel/Sliders'

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import { SwiperProps, SwiperSlide } from 'swiper/react';
import { Project } from '../components/Projects/Carrousel/Project';
import { Header } from '../components/Header';
import Head from 'next/head';

import {v4 as uuid} from 'uuid'



export default function Projetos() {
    const settings: SwiperProps = {
        spaceBetween: 100,
        slidesPerView: 1,
        navigation: true,
        pagination: {
            clickable: true
        },

    }
    return (
        <>
            <Head>
                <title>Anderson Dias | Projetos</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <div className="w-full h-[calc(100vh-64px)] flex items-center justify-center flex-wrap degrade ">
                <div className="container ">
                    <Sliders settings={settings}>
                        {sliders.map((slider, index) => {
                            return (
                                <SwiperSlide key={index}>
                                    <Project
                                        title={slider.title}
                                        description={slider.description}
                                        image={slider.image}
                                        visitPage={slider.visitPage}
                                        repository={slider.repository}
                                        key={slider.id}
                                    />
                                </SwiperSlide>
                            )
                        })}
                    </Sliders>
                </div>
            </div>
        </>
    )
}

const sliders = [
    {
        id: uuid(),
        title: 'Desafio Naped',
        description: 'Projeto realizado para resolver um desafio da comunidade codelândia do Iuri Silva. É um blog com conteúdo voltado para o público "nerd".',
        image: "projeto-1",
        visitPage: "https://naped-desafio-ten.vercel.app",
        repository: "https://github.com/andersonDias89/naped"
    },

    {
        id: uuid(),
        title: 'Site Academia',
        description: 'Projeto criado para portfólio.Trata-se de um site para academia divulgando os seus serviços',
        image: "projeto-2",
        visitPage: "https://academia-projeto.web.app/",
        repository: "https://github.com/andersonDias89/academia-treino"
    },

    {
        id: uuid(),
        title: 'Projeto Rachi',
        description: 'Desafio proposto por Iuri Silva para desenvolver um web site da empresa Rachi',
        image: "projeto-3",
        visitPage: "https://projeto-rachi.web.app/",
        repository: "https://github.com/andersonDias89/rachi-desafio"
    },

]


export async function getStaticProps() {
    return {
      props: {
        
      },
    }
  }