import 'swiper/css'
import { Sliders } from '../components/Projects/Carrousel/Sliders'

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import { SwiperProps, SwiperSlide } from 'swiper/react';
import { Project } from '../components/Projects/Carrousel/Project';
import { Header } from '../components/Header';
import Head from 'next/head';



import { api } from '../server/axios';



export default function Projetos({projects}) { 
    const settings: SwiperProps = {
        spaceBetween: 100,
        slidesPerView: 1,
        navigation: true,
        pagination: {
            clickable: true
        },

    }
    return (
        <>
            <Head>
                <title>Anderson Dias | Projetos</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <div className="w-full h-[calc(100vh-64px)] flex items-center justify-center flex-wrap degrade ">
                <div className="container ">
                    <Sliders settings={settings}>
                        {projects.map((slider, index) => {
                            return (
                                <SwiperSlide key={index}>
                                    <Project
                                        title={slider.title}
                                        description={slider.description}
                                        image={slider.image}
                                        visitPage={slider.visitPage}
                                        repository={slider.repository}
                                        id={slider.id}
                                        key={slider.id}
                                    />
                                </SwiperSlide>
                            )
                        })}
                    </Sliders>
                </div>
            </div>
        </>
    )
}

export const getStaticProps = async () => {
    const res = await api.get('/projetos');
    console.log(res.data);
    return {
        props: {
            projects: res.data,
        },
        
        revalidate: 60 * 60 * 24,
    }
    
}