import 'swiper/css'
import { Sliders } from '../components/Projects/Carrousel/Sliders'

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import { SwiperProps, SwiperSlide } from 'swiper/react';
import { Project } from '../components/Projects/Carrousel/Project';
import { Header } from '../components/Header';
import Head from 'next/head';

import {v4 as uuid} from 'uuid'



export default function Projetos() {
    const settings: SwiperProps = {
        spaceBetween: 100,
        slidesPerView: 1,
        navigation: true,
        pagination: {
            clickable: true
        },

    }
    return (
        <>
            <Head>
                <title>Anderson Dias | Projetos</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <div className="w-full h-[calc(100vh-64px)] flex items-center justify-center flex-wrap degrade ">
                <div className="container ">
                    <Sliders settings={settings}>
                        {sliders.map((slider, index) => {
                            return (
                                <SwiperSlide key={index}>
                                    <Project
                                        title={slider.title}
                                        description={slider.description}
                                        image={slider.image}
                                        visitPage={slider.visitPage}
                                        repository={slider.repository}
                                        key={slider.id}
                                    />
                                </SwiperSlide>
                            )
                        })}
                    </Sliders>
                </div>
            </div>
        </>
    )
}

const sliders = [
    {
        id: uuid(),
        title: 'Projeto 1',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur amet beatae facilis soluta. Ex nesciunt evenieteligendi nulla, cumque sint reprehenderit sit aperiamreiciendis culpa quibusdam.',
        image: "assets/example.jpg",
        visitPage: "https://andersondiasdev.web.app",
        repository: "https://github.com/andersonDias89"
    },

    {
        id: uuid(),
        title: 'Projeto 2',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur amet beatae facilis soluta. Ex nesciunt evenieteligendi nulla, cumque sint reprehenderit sit aperiamreiciendis culpa quibusdam.',
        image: "assets/example2.jpg",
        visitPage: "https://andersondiasdev.web.app",
        repository: "https://github.com/andersonDias89"
    },

    {
        id: uuid(),
        title: 'Projeto 3',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur amet beatae facilis soluta. Ex nesciunt evenieteligendi nulla, cumque sint reprehenderit sit aperiamreiciendis culpa quibusdam.',
        image: "assets/example3.jpg",
        visitPage: "https://andersondiasdev.web.app",
        repository: "https://github.com/andersonDias89"
    },

]


export async function getStaticProps() {
    return {
      props: {
        
      },
    }
  }